/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.gradle.core.models.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IItem extends Serializable {

	/**
	 * Setter for <code>gradle.item.id</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>gradle.item.id</code>.
	 */
	public Long getId();

	/**
	 * Setter for <code>gradle.item.dateCreate</code>.
	 */
	public void setDatecreate(Timestamp value);

	/**
	 * Getter for <code>gradle.item.dateCreate</code>.
	 */
	public Timestamp getDatecreate();

	/**
	 * Setter for <code>gradle.item.name</code>.
	 */
	public void setName(String value);

	/**
	 * Getter for <code>gradle.item.name</code>.
	 */
	public String getName();

	/**
	 * Setter for <code>gradle.item.stock</code>.
	 */
	public void setStock(Long value);

	/**
	 * Getter for <code>gradle.item.stock</code>.
	 */
	public Long getStock();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IItem
	 */
	public void from(io.github.picodotdev.gradle.core.models.tables.interfaces.IItem from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IItem
	 */
	public <E extends io.github.picodotdev.gradle.core.models.tables.interfaces.IItem> E into(E into);
}
