/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.springboot.jooq.tables.pojos;


import io.github.picodotdev.blogbitix.springboot.jooq.tables.interfaces.IEmployee;

import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee implements IEmployee {

	private static final long serialVersionUID = -925886335;

	private Long          id;
	private String        name;
	private String        surname;
	private LocalDateTime birthday;

	public Employee() {}

	public Employee(Employee value) {
		this.id = value.id;
		this.name = value.name;
		this.surname = value.surname;
		this.birthday = value.birthday;
	}

	public Employee(
		Long          id,
		String        name,
		String        surname,
		LocalDateTime birthday
	) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.birthday = birthday;
	}

	@NotNull
	@Override
	public Long getId() {
		return this.id;
	}

	@Override
	public void setId(Long id) {
		this.id = id;
	}

	@Size(max = 256)
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public void setName(String name) {
		this.name = name;
	}

	@Size(max = 256)
	@Override
	public String getSurname() {
		return this.surname;
	}

	@Override
	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Override
	public LocalDateTime getBirthday() {
		return this.birthday;
	}

	@Override
	public void setBirthday(LocalDateTime birthday) {
		this.birthday = birthday;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Employee (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(surname);
		sb.append(", ").append(birthday);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IEmployee from) {
		setId(from.getId());
		setName(from.getName());
		setSurname(from.getSurname());
		setBirthday(from.getBirthday());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IEmployee> E into(E into) {
		into.from(this);
		return into;
	}
}
