# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "ubuntu-docker" do |instance|
    instance.vm.box = "ubuntu/bionic64"

    instance.vm.provider :virtualbox do |vb|
      vb.name = "Ubuntu Docker (Vagrant)"
    end

    instance.vm.network "private_network", ip: "192.168.33.10"

    instance.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"

      instance.vm.provision "file", source: "docker-compose.yml", destination: "/home/vagrant/docker-compose.yml"
      instance.vm.provision "shell", inline: $docker_role_script
    end
  end

  $docker_role_script = <<-SCRIPT
    echo "Updating..."
    sudo apt-get update
    sudo apt-get upgrade

    echo "Installing docker..."
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    sudo usermod -aG docker vagrant

    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

    echo "Starting Docker service..."
    sudo systemctl daemon-reload
    sudo systemctl enable docker.service
    sudo systemctl start docker.service
  SCRIPT
end
