spring:
  application:
    name: ZalandoLogbook

logging:
    level:
      root: "info"
      org.zalando.logbook.Logbook: "trace"
      io.github.picodotdev.blogbitix: "info"
    pattern:
      level: "%-5level"
      console: "%d{DEFAULT} %X{uuid} %-5level %X{correlation} %60.60logger %msg%n"

logbook:
  strategy: without-body
