/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.pojos;


import io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.interfaces.IItem;

import java.math.BigDecimal;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.joda.time.DateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Item implements IItem {

	private static final long serialVersionUID = 1172610886;

	private Long       id;
	private DateTime   creationdate;
	private String     name;
	private String     description;
	private Long       stock;
	private BigDecimal price;

	public Item() {}

	public Item(Item value) {
		this.id = value.id;
		this.creationdate = value.creationdate;
		this.name = value.name;
		this.description = value.description;
		this.stock = value.stock;
		this.price = value.price;
	}

	public Item(
		Long       id,
		DateTime   creationdate,
		String     name,
		String     description,
		Long       stock,
		BigDecimal price
	) {
		this.id = id;
		this.creationdate = creationdate;
		this.name = name;
		this.description = description;
		this.stock = stock;
		this.price = price;
	}

	@NotNull
	@Override
	public Long getId() {
		return this.id;
	}

	@Override
	public void setId(Long id) {
		this.id = id;
	}

	@Override
	public DateTime getCreationdate() {
		return this.creationdate;
	}

	@Override
	public void setCreationdate(DateTime creationdate) {
		this.creationdate = creationdate;
	}

	@Size(max = 256)
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public void setName(String name) {
		this.name = name;
	}

	@Size(max = 2147483647)
	@Override
	public String getDescription() {
		return this.description;
	}

	@Override
	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public Long getStock() {
		return this.stock;
	}

	@Override
	public void setStock(Long stock) {
		this.stock = stock;
	}

	@Override
	public BigDecimal getPrice() {
		return this.price;
	}

	@Override
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Item (");

		sb.append(id);
		sb.append(", ").append(creationdate);
		sb.append(", ").append(name);
		sb.append(", ").append(description);
		sb.append(", ").append(stock);
		sb.append(", ").append(price);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IItem from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
		setName(from.getName());
		setDescription(from.getDescription());
		setStock(from.getStock());
		setPrice(from.getPrice());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IItem> E into(E into) {
		into.from(this);
		return into;
	}
}
