/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IItem extends Serializable {

	/**
	 * Setter for <code>INVENTORY.ITEM.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>INVENTORY.ITEM.ID</code>.
	 */
	@NotNull
	public Long getId();

	/**
	 * Setter for <code>INVENTORY.ITEM.CREATIONDATE</code>.
	 */
	public void setCreationdate(LocalDateTime value);

	/**
	 * Getter for <code>INVENTORY.ITEM.CREATIONDATE</code>.
	 */
	public LocalDateTime getCreationdate();

	/**
	 * Setter for <code>INVENTORY.ITEM.NAME</code>.
	 */
	public void setName(String value);

	/**
	 * Getter for <code>INVENTORY.ITEM.NAME</code>.
	 */
	@Size(max = 256)
	public String getName();

	/**
	 * Setter for <code>INVENTORY.ITEM.DESCRIPTION</code>.
	 */
	public void setDescription(String value);

	/**
	 * Getter for <code>INVENTORY.ITEM.DESCRIPTION</code>.
	 */
	@Size(max = 2147483647)
	public String getDescription();

	/**
	 * Setter for <code>INVENTORY.ITEM.STOCK</code>.
	 */
	public void setStock(Long value);

	/**
	 * Getter for <code>INVENTORY.ITEM.STOCK</code>.
	 */
	public Long getStock();

	/**
	 * Setter for <code>INVENTORY.ITEM.PRICE</code>.
	 */
	public void setPrice(BigDecimal value);

	/**
	 * Getter for <code>INVENTORY.ITEM.PRICE</code>.
	 */
	public BigDecimal getPrice();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IItem
	 */
	public void from(io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.interfaces.IItem from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IItem
	 */
	public <E extends io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.interfaces.IItem> E into(E into);
}
