# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.disk :disk, size: "10GB", primary: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Clouding Site"
    vb.memory = "1024"
  end
end
