/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;
import io.github.picodotdev.plugintapestry.entities.jooq.tables.records.ProductoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * PLUGINTAPESTRY.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProductoRecord> PK_PRODUCTO = Internal.createUniqueKey(Producto.PRODUCTO, DSL.name("PK_PRODUCTO"), new TableField[] { Producto.PRODUCTO.ID }, true);
}
