/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plugintapestry extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PLUGINTAPESTRY</code>
     */
    public static final Plugintapestry PLUGINTAPESTRY = new Plugintapestry();

    /**
     * The table <code>PLUGINTAPESTRY.PRODUCTO</code>.
     */
    public final Producto PRODUCTO = Producto.PRODUCTO;

    /**
     * No further instances allowed
     */
    private Plugintapestry() {
        super("PLUGINTAPESTRY", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Producto.PRODUCTO);
    }
}
