/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;


/**
 * Convenience access to all tables in PLUGINTAPESTRY.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PLUGINTAPESTRY.PRODUCTO</code>.
     */
    public static final Producto PRODUCTO = Producto.PRODUCTO;
}
