/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.gradle.core.models;


import io.github.picodotdev.gradle.core.models.Sequences;
import io.github.picodotdev.gradle.core.models.tables.Item;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gradle extends SchemaImpl {

	private static final long serialVersionUID = 1962772334;

	/**
	 * The reference instance of <code>gradle</code>
	 */
	public static final Gradle GRADLE = new Gradle();

	/**
	 * No further instances allowed
	 */
	private Gradle() {
		super("gradle");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.ITEM_ID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Item.ITEM);
	}
}
