/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.gradle.core.models;


import io.github.picodotdev.gradle.core.models.Gradle;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in gradle
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>gradle.item_id_seq</code>
	 */
	public static final Sequence<Long> ITEM_ID_SEQ = new SequenceImpl<Long>("item_id_seq", Gradle.GRADLE, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
