/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.gradle.core.models;


import io.github.picodotdev.gradle.core.models.tables.Item;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in gradle
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table gradle.item
	 */
	public static final Item ITEM = io.github.picodotdev.gradle.core.models.tables.Item.ITEM;
}
