/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables;


import io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.Inventory;
import io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.Keys;
import io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.records.ItemRecord;
import io.github.picodotdev.blogbitix.multidatabase.misc.TimestampConverter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Item extends TableImpl<ItemRecord> {

	private static final long serialVersionUID = -1313983264;

	/**
	 * The reference instance of <code>INVENTORY.ITEM</code>
	 */
	public static final Item ITEM = new Item();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ItemRecord> getRecordType() {
		return ItemRecord.class;
	}

	/**
	 * The column <code>INVENTORY.ITEM.ID</code>.
	 */
	public final TableField<ItemRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>INVENTORY.ITEM.CREATIONDATE</code>.
	 */
	public final TableField<ItemRecord, LocalDateTime> CREATIONDATE = createField("CREATIONDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new TimestampConverter());

	/**
	 * The column <code>INVENTORY.ITEM.NAME</code>.
	 */
	public final TableField<ItemRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>INVENTORY.ITEM.DESCRIPTION</code>.
	 */
	public final TableField<ItemRecord, String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>INVENTORY.ITEM.STOCK</code>.
	 */
	public final TableField<ItemRecord, Long> STOCK = createField("STOCK", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>INVENTORY.ITEM.PRICE</code>.
	 */
	public final TableField<ItemRecord, BigDecimal> PRICE = createField("PRICE", org.jooq.impl.SQLDataType.DECIMAL.precision(7, 2), this, "");

	/**
	 * Create a <code>INVENTORY.ITEM</code> table reference
	 */
	public Item() {
		this("ITEM", null);
	}

	/**
	 * Create an aliased <code>INVENTORY.ITEM</code> table reference
	 */
	public Item(String alias) {
		this(alias, ITEM);
	}

	private Item(String alias, Table<ItemRecord> aliased) {
		this(alias, aliased, null);
	}

	private Item(String alias, Table<ItemRecord> aliased, Field<?>[] parameters) {
		super(alias, Inventory.INVENTORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ItemRecord, Long> getIdentity() {
		return Keys.IDENTITY_ITEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ItemRecord> getPrimaryKey() {
		return Keys.PK_ITEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ItemRecord>> getKeys() {
		return Arrays.<UniqueKey<ItemRecord>>asList(Keys.PK_ITEM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Item as(String alias) {
		return new Item(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Item rename(String name) {
		return new Item(name, null);
	}
}
