/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_picodotdev_blogbitix_javaraspberrypi_Dht11 */

#ifndef _Included_io_github_picodotdev_blogbitix_javaraspberrypi_Dht11
#define _Included_io_github_picodotdev_blogbitix_javaraspberrypi_Dht11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_picodotdev_blogbitix_javaraspberrypi_Dht11
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_picodotdev_blogbitix_javaraspberrypi_Dht11_init
  (JNIEnv *, jobject);

/*
 * Class:     io_github_picodotdev_blogbitix_javaraspberrypi_Dht11
 * Method:    read
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_picodotdev_blogbitix_javaraspberrypi_Dht11_read
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
