/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_picodotdev_blogbitix_javaraspberrypi_JniHelloWorld */

#ifndef _Included_io_github_picodotdev_blogbitix_javaraspberrypi_JniHelloWorld
#define _Included_io_github_picodotdev_blogbitix_javaraspberrypi_JniHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_picodotdev_blogbitix_javaraspberrypi_JniHelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_picodotdev_blogbitix_javaraspberrypi_JniHelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
