/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.springboot.jooq;


import io.github.picodotdev.blogbitix.springboot.jooq.tables.Department;
import io.github.picodotdev.blogbitix.springboot.jooq.tables.Employee;
import io.github.picodotdev.blogbitix.springboot.jooq.tables.EmployeeDepartment;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

	private static final long serialVersionUID = 1510978803;

	/**
	 * The reference instance of <code>JOOQ</code>
	 */
	public static final Jooq JOOQ = new Jooq();

	/**
	 * No further instances allowed
	 */
	private Jooq() {
		super("JOOQ");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_2A0C927D_2B70_4F7E_A1D1_03C1F7136570,
			Sequences.SYSTEM_SEQUENCE_60544CAA_ED29_4D11_A68C_598713FAA78C,
			Sequences.SYSTEM_SEQUENCE_66D2E125_9F1E_42B0_B9B2_399AC2C6B6D6);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Employee.EMPLOYEE,
			Department.DEPARTMENT,
			EmployeeDepartment.EMPLOYEE_DEPARTMENT);
	}
}
