/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.springboot.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in JOOQ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>JOOQ.SYSTEM_SEQUENCE_2A0C927D_2B70_4F7E_A1D1_03C1F7136570</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_2A0C927D_2B70_4F7E_A1D1_03C1F7136570 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2A0C927D_2B70_4F7E_A1D1_03C1F7136570", Jooq.JOOQ, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>JOOQ.SYSTEM_SEQUENCE_60544CAA_ED29_4D11_A68C_598713FAA78C</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_60544CAA_ED29_4D11_A68C_598713FAA78C = new SequenceImpl<Long>("SYSTEM_SEQUENCE_60544CAA_ED29_4D11_A68C_598713FAA78C", Jooq.JOOQ, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>JOOQ.SYSTEM_SEQUENCE_66D2E125_9F1E_42B0_B9B2_399AC2C6B6D6</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_66D2E125_9F1E_42B0_B9B2_399AC2C6B6D6 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_66D2E125_9F1E_42B0_B9B2_399AC2C6B6D6", Jooq.JOOQ, org.jooq.impl.SQLDataType.BIGINT);
}
