/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.springboot.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in JOOQ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>JOOQ.SYSTEM_SEQUENCE_50DF79A2_56EC_4A82_9556_8D4D02464C70</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_50DF79A2_56EC_4A82_9556_8D4D02464C70 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_50DF79A2_56EC_4A82_9556_8D4D02464C70", Jooq.JOOQ, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>JOOQ.SYSTEM_SEQUENCE_7E0B2DED_FDE0_4E46_83B6_4680A47BA415</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_7E0B2DED_FDE0_4E46_83B6_4680A47BA415 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_7E0B2DED_FDE0_4E46_83B6_4680A47BA415", Jooq.JOOQ, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>JOOQ.SYSTEM_SEQUENCE_D497824B_20C5_42FE_8B14_88BF32D119DF</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_D497824B_20C5_42FE_8B14_88BF32D119DF = new SequenceImpl<Long>("SYSTEM_SEQUENCE_D497824B_20C5_42FE_8B14_88BF32D119DF", Jooq.JOOQ, org.jooq.impl.SQLDataType.BIGINT);
}
