/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.springboot.jooq;


import javax.annotation.Generated;

import io.github.picodotdev.blogbitix.springboot.jooq.tables.Department;
import io.github.picodotdev.blogbitix.springboot.jooq.tables.Employee;
import io.github.picodotdev.blogbitix.springboot.jooq.tables.EmployeeDepartment;


/**
 * Convenience access to all tables in JOOQ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table JOOQ.EMPLOYEE
	 */
	public static final Employee EMPLOYEE = io.github.picodotdev.blogbitix.springboot.jooq.tables.Employee.EMPLOYEE;

	/**
	 * The table JOOQ.DEPARTMENT
	 */
	public static final Department DEPARTMENT = io.github.picodotdev.blogbitix.springboot.jooq.tables.Department.DEPARTMENT;

	/**
	 * The table JOOQ.EMPLOYEE_DEPARTMENT
	 */
	public static final EmployeeDepartment EMPLOYEE_DEPARTMENT = io.github.picodotdev.blogbitix.springboot.jooq.tables.EmployeeDepartment.EMPLOYEE_DEPARTMENT;
}
