/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq.tables.pojos;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.interfaces.IProducto;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Producto implements IProducto {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        nombre;
    private String        descripcion;
    private Long          cantidad;
    private LocalDateTime fecha;

    public Producto() {}

    public Producto(IProducto value) {
        this.id = value.getId();
        this.nombre = value.getNombre();
        this.descripcion = value.getDescripcion();
        this.cantidad = value.getCantidad();
        this.fecha = value.getFecha();
    }

    public Producto(
        Long          id,
        String        nombre,
        String        descripcion,
        Long          cantidad,
        LocalDateTime fecha
    ) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.cantidad = cantidad;
        this.fecha = fecha;
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.ID</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.ID</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.NOMBRE</code>.
     */
    @NotNull
    @Size(max = 100)
    @Override
    public String getNombre() {
        return this.nombre;
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.NOMBRE</code>.
     */
    @Override
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.DESCRIPCION</code>.
     */
    @NotNull
    @Size(max = 5000)
    @Override
    public String getDescripcion() {
        return this.descripcion;
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.DESCRIPCION</code>.
     */
    @Override
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.CANTIDAD</code>.
     */
    @Override
    public Long getCantidad() {
        return this.cantidad;
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.CANTIDAD</code>.
     */
    @Override
    public void setCantidad(Long cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.FECHA</code>.
     */
    @Override
    public LocalDateTime getFecha() {
        return this.fecha;
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.FECHA</code>.
     */
    @Override
    public void setFecha(LocalDateTime fecha) {
        this.fecha = fecha;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Producto (");

        sb.append(id);
        sb.append(", ").append(nombre);
        sb.append(", ").append(descripcion);
        sb.append(", ").append(cantidad);
        sb.append(", ").append(fecha);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProducto from) {
        setId(from.getId());
        setNombre(from.getNombre());
        setDescripcion(from.getDescripcion());
        setCantidad(from.getCantidad());
        setFecha(from.getFecha());
    }

    @Override
    public <E extends IProducto> E into(E into) {
        into.from(this);
        return into;
    }
}
