/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.gradle.core.models.tables.records;


import io.github.picodotdev.gradle.core.models.tables.Item;
import io.github.picodotdev.gradle.core.models.tables.interfaces.IItem;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record4<Long, Timestamp, String, Long>, IItem {

	private static final long serialVersionUID = 1147583140;

	/**
	 * Setter for <code>gradle.item.id</code>.
	 */
	@Override
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>gradle.item.id</code>.
	 */
	@Override
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>gradle.item.dateCreate</code>.
	 */
	@Override
	public void setDatecreate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>gradle.item.dateCreate</code>.
	 */
	@Override
	public Timestamp getDatecreate() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>gradle.item.name</code>.
	 */
	@Override
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>gradle.item.name</code>.
	 */
	@Override
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>gradle.item.stock</code>.
	 */
	@Override
	public void setStock(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>gradle.item.stock</code>.
	 */
	@Override
	public Long getStock() {
		return (Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Timestamp, String, Long> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Timestamp, String, Long> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Item.ITEM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Item.ITEM.DATECREATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Item.ITEM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return Item.ITEM.STOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getDatecreate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getStock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value2(Timestamp value) {
		setDatecreate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value4(Long value) {
		setStock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord values(Long value1, Timestamp value2, String value3, Long value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IItem from) {
		setId(from.getId());
		setDatecreate(from.getDatecreate());
		setName(from.getName());
		setStock(from.getStock());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IItem> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItemRecord
	 */
	public ItemRecord() {
		super(Item.ITEM);
	}

	/**
	 * Create a detached, initialised ItemRecord
	 */
	public ItemRecord(Long id, Timestamp datecreate, String name, Long stock) {
		super(Item.ITEM);

		setValue(0, id);
		setValue(1, datecreate);
		setValue(2, name);
		setValue(3, stock);
	}
}
