/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq.tables.records;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;
import io.github.picodotdev.plugintapestry.entities.jooq.tables.interfaces.IProducto;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductoRecord extends UpdatableRecordImpl<ProductoRecord> implements Record5<Long, String, String, Long, LocalDateTime>, IProducto {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.ID</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.ID</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.NOMBRE</code>.
     */
    @Override
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.NOMBRE</code>.
     */
    @NotNull
    @Size(max = 100)
    @Override
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.DESCRIPCION</code>.
     */
    @Override
    public void setDescripcion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.DESCRIPCION</code>.
     */
    @NotNull
    @Size(max = 5000)
    @Override
    public String getDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.CANTIDAD</code>.
     */
    @Override
    public void setCantidad(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.CANTIDAD</code>.
     */
    @Override
    public Long getCantidad() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.FECHA</code>.
     */
    @Override
    public void setFecha(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.FECHA</code>.
     */
    @Override
    public LocalDateTime getFecha() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Long, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Long, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Producto.PRODUCTO.ID;
    }

    @Override
    public Field<String> field2() {
        return Producto.PRODUCTO.NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return Producto.PRODUCTO.DESCRIPCION;
    }

    @Override
    public Field<Long> field4() {
        return Producto.PRODUCTO.CANTIDAD;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Producto.PRODUCTO.FECHA;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public String component3() {
        return getDescripcion();
    }

    @Override
    public Long component4() {
        return getCantidad();
    }

    @Override
    public LocalDateTime component5() {
        return getFecha();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public String value3() {
        return getDescripcion();
    }

    @Override
    public Long value4() {
        return getCantidad();
    }

    @Override
    public LocalDateTime value5() {
        return getFecha();
    }

    @Override
    public ProductoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProductoRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public ProductoRecord value3(String value) {
        setDescripcion(value);
        return this;
    }

    @Override
    public ProductoRecord value4(Long value) {
        setCantidad(value);
        return this;
    }

    @Override
    public ProductoRecord value5(LocalDateTime value) {
        setFecha(value);
        return this;
    }

    @Override
    public ProductoRecord values(Long value1, String value2, String value3, Long value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IProducto from) {
        setId(from.getId());
        setNombre(from.getNombre());
        setDescripcion(from.getDescripcion());
        setCantidad(from.getCantidad());
        setFecha(from.getFecha());
    }

    @Override
    public <E extends IProducto> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductoRecord
     */
    public ProductoRecord() {
        super(Producto.PRODUCTO);
    }

    /**
     * Create a detached, initialised ProductoRecord
     */
    public ProductoRecord(Long id, String nombre, String descripcion, Long cantidad, LocalDateTime fecha) {
        super(Producto.PRODUCTO);

        setId(id);
        setNombre(nombre);
        setDescripcion(descripcion);
        setCantidad(cantidad);
        setFecha(fecha);
    }
}
