/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.purchases.tables.pojos;


import io.github.picodotdev.blogbitix.multidatabase.jooq.purchases.tables.interfaces.IPurchase;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Purchase implements IPurchase {

	private static final long serialVersionUID = 1478018264;

	private Long          id;
	private LocalDateTime creationdate;
	private Long          quantity;
	private BigDecimal    price;
	private Long          itemId;

	public Purchase() {}

	public Purchase(Purchase value) {
		this.id = value.id;
		this.creationdate = value.creationdate;
		this.quantity = value.quantity;
		this.price = value.price;
		this.itemId = value.itemId;
	}

	public Purchase(
		Long          id,
		LocalDateTime creationdate,
		Long          quantity,
		BigDecimal    price,
		Long          itemId
	) {
		this.id = id;
		this.creationdate = creationdate;
		this.quantity = quantity;
		this.price = price;
		this.itemId = itemId;
	}

	@NotNull
	@Override
	public Long getId() {
		return this.id;
	}

	@Override
	public void setId(Long id) {
		this.id = id;
	}

	@Override
	public LocalDateTime getCreationdate() {
		return this.creationdate;
	}

	@Override
	public void setCreationdate(LocalDateTime creationdate) {
		this.creationdate = creationdate;
	}

	@Override
	public Long getQuantity() {
		return this.quantity;
	}

	@Override
	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	@Override
	public BigDecimal getPrice() {
		return this.price;
	}

	@Override
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Override
	public Long getItemId() {
		return this.itemId;
	}

	@Override
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Purchase (");

		sb.append(id);
		sb.append(", ").append(creationdate);
		sb.append(", ").append(quantity);
		sb.append(", ").append(price);
		sb.append(", ").append(itemId);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IPurchase from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
		setQuantity(from.getQuantity());
		setPrice(from.getPrice());
		setItemId(from.getItemId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IPurchase> E into(E into) {
		into.from(this);
		return into;
	}
}
