server:
  port: ${port:8085}

zuul:
  routes:
    service: '/service/**'
  retryable: true

hystrix:
  command:
    service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    circuitBreaker:
      requestVolumeThreshold: 4
      errorThresholdPercentage: 50

service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 2000
    MaxTotalHttpConnections: 100
    MaxConnectionsPerHost: 100
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 2
    ServerListRefreshInterval: 2000
    OkToRetryOnAllOperations: true
    retryableStatusCodes: 500,404
