/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.records;


import io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.Item;
import io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.interfaces.IItem;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record6<Long, LocalDateTime, String, String, Long, BigDecimal>, IItem {

	private static final long serialVersionUID = 357535426;

	/**
	 * Setter for <code>INVENTORY.ITEM.ID</code>.
	 */
	@Override
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>INVENTORY.ITEM.ID</code>.
	 */
	@NotNull
	@Override
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>INVENTORY.ITEM.CREATIONDATE</code>.
	 */
	@Override
	public void setCreationdate(LocalDateTime value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>INVENTORY.ITEM.CREATIONDATE</code>.
	 */
	@Override
	public LocalDateTime getCreationdate() {
		return (LocalDateTime) getValue(1);
	}

	/**
	 * Setter for <code>INVENTORY.ITEM.NAME</code>.
	 */
	@Override
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>INVENTORY.ITEM.NAME</code>.
	 */
	@Size(max = 256)
	@Override
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>INVENTORY.ITEM.DESCRIPTION</code>.
	 */
	@Override
	public void setDescription(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>INVENTORY.ITEM.DESCRIPTION</code>.
	 */
	@Size(max = 2147483647)
	@Override
	public String getDescription() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>INVENTORY.ITEM.STOCK</code>.
	 */
	@Override
	public void setStock(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>INVENTORY.ITEM.STOCK</code>.
	 */
	@Override
	public Long getStock() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>INVENTORY.ITEM.PRICE</code>.
	 */
	@Override
	public void setPrice(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>INVENTORY.ITEM.PRICE</code>.
	 */
	@Override
	public BigDecimal getPrice() {
		return (BigDecimal) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, LocalDateTime, String, String, Long, BigDecimal> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, LocalDateTime, String, String, Long, BigDecimal> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Item.ITEM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<LocalDateTime> field2() {
		return Item.ITEM.CREATIONDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Item.ITEM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Item.ITEM.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return Item.ITEM.STOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return Item.ITEM.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LocalDateTime value2() {
		return getCreationdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getStock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value2(LocalDateTime value) {
		setCreationdate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value5(Long value) {
		setStock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value6(BigDecimal value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord values(Long value1, LocalDateTime value2, String value3, String value4, Long value5, BigDecimal value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(IItem from) {
		setId(from.getId());
		setCreationdate(from.getCreationdate());
		setName(from.getName());
		setDescription(from.getDescription());
		setStock(from.getStock());
		setPrice(from.getPrice());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends IItem> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItemRecord
	 */
	public ItemRecord() {
		super(Item.ITEM);
	}

	/**
	 * Create a detached, initialised ItemRecord
	 */
	public ItemRecord(Long id, LocalDateTime creationdate, String name, String description, Long stock, BigDecimal price) {
		super(Item.ITEM);

		setValue(0, id);
		setValue(1, creationdate);
		setValue(2, name);
		setValue(3, description);
		setValue(4, stock);
		setValue(5, price);
	}
}
