/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.springboot.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDepartment extends Serializable {

	/**
	 * Setter for <code>JOOQ.DEPARTMENT.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>JOOQ.DEPARTMENT.ID</code>.
	 */
	@NotNull
	public Long getId();

	/**
	 * Setter for <code>JOOQ.DEPARTMENT.NAME</code>.
	 */
	public void setName(String value);

	/**
	 * Getter for <code>JOOQ.DEPARTMENT.NAME</code>.
	 */
	@NotNull
	@Size(max = 256)
	public String getName();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IDepartment
	 */
	public void from(io.github.picodotdev.blogbitix.springboot.jooq.tables.interfaces.IDepartment from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IDepartment
	 */
	public <E extends io.github.picodotdev.blogbitix.springboot.jooq.tables.interfaces.IDepartment> E into(E into);
}
