/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.springboot.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IEmployeeDepartment extends Serializable {

	/**
	 * Setter for <code>JOOQ.EMPLOYEE_DEPARTMENT.ID</code>.
	 */
	public void setId(Long value);

	/**
	 * Getter for <code>JOOQ.EMPLOYEE_DEPARTMENT.ID</code>.
	 */
	@NotNull
	public Long getId();

	/**
	 * Setter for <code>JOOQ.EMPLOYEE_DEPARTMENT.EMPLOYEE_ID</code>.
	 */
	public void setEmployeeId(Long value);

	/**
	 * Getter for <code>JOOQ.EMPLOYEE_DEPARTMENT.EMPLOYEE_ID</code>.
	 */
	public Long getEmployeeId();

	/**
	 * Setter for <code>JOOQ.EMPLOYEE_DEPARTMENT.DEPARTMENT_ID</code>.
	 */
	public void setDepartmentId(Long value);

	/**
	 * Getter for <code>JOOQ.EMPLOYEE_DEPARTMENT.DEPARTMENT_ID</code>.
	 */
	public Long getDepartmentId();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface IEmployeeDepartment
	 */
	public void from(io.github.picodotdev.blogbitix.springboot.jooq.tables.interfaces.IEmployeeDepartment from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface IEmployeeDepartment
	 */
	public <E extends io.github.picodotdev.blogbitix.springboot.jooq.tables.interfaces.IEmployeeDepartment> E into(E into);
}
