/*
 * This file is generated by jOOQ.
*/
package io.github.picodotdev.plugintapestry.entities.jooq;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>PLUGINTAPESTRY</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index PRIMARY_KEY_F = createIndex("PRIMARY_KEY_F", Producto.PRODUCTO, new OrderField[] { Producto.PRODUCTO.ID }, true);
    }
}
