/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.plugintapestry.entities.jooq;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plugintapestry extends SchemaImpl {

	private static final long serialVersionUID = 1746345342;

	/**
	 * The reference instance of <code>PLUGINTAPESTRY</code>
	 */
	public static final Plugintapestry PLUGINTAPESTRY = new Plugintapestry();

	/**
	 * No further instances allowed
	 */
	private Plugintapestry() {
		super("PLUGINTAPESTRY");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_2F89BFCF_CA7D_403A_A776_BEB1858DA866);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Producto.PRODUCTO);
	}
}
