/*
 * This file is generated by jOOQ.
*/
package io.github.picodotdev.plugintapestry.entities.jooq;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plugintapestry extends SchemaImpl {

    private static final long serialVersionUID = 376920727;

    /**
     * The reference instance of <code>PLUGINTAPESTRY</code>
     */
    public static final Plugintapestry PLUGINTAPESTRY = new Plugintapestry();

    /**
     * The table <code>PLUGINTAPESTRY.PRODUCTO</code>.
     */
    public final Producto PRODUCTO = io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto.PRODUCTO;

    /**
     * No further instances allowed
     */
    private Plugintapestry() {
        super("PLUGINTAPESTRY", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Producto.PRODUCTO);
    }
}
