/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.plugintapestry.entities.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PLUGINTAPESTRY
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PLUGINTAPESTRY.SYSTEM_SEQUENCE_2F89BFCF_CA7D_403A_A776_BEB1858DA866</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_2F89BFCF_CA7D_403A_A776_BEB1858DA866 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2F89BFCF_CA7D_403A_A776_BEB1858DA866", Plugintapestry.PLUGINTAPESTRY, org.jooq.impl.SQLDataType.BIGINT);
}
