/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq;


import io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PLUGINTAPESTRY
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PLUGINTAPESTRY.PRODUCTO</code>.
     */
    public static final Producto PRODUCTO = io.github.picodotdev.plugintapestry.entities.jooq.tables.Producto.PRODUCTO;
}
