/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.inventory;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in INVENTORY
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>INVENTORY.SYSTEM_SEQUENCE_3339D621_D29B_41D9_A6A5_D62F3C8AF087</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_3339D621_D29B_41D9_A6A5_D62F3C8AF087 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_3339D621_D29B_41D9_A6A5_D62F3C8AF087", Inventory.INVENTORY, org.jooq.impl.SQLDataType.BIGINT);
}
