/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.inventory;


import io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.Item;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in INVENTORY
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table INVENTORY.ITEM
	 */
	public static final Item ITEM = io.github.picodotdev.blogbitix.multidatabase.jooq.inventory.tables.Item.ITEM;
}
