/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq.tables;


import io.github.picodotdev.plugintapestry.entities.jooq.Keys;
import io.github.picodotdev.plugintapestry.entities.jooq.Plugintapestry;
import io.github.picodotdev.plugintapestry.entities.jooq.tables.records.ProductoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Producto extends TableImpl<ProductoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PLUGINTAPESTRY.PRODUCTO</code>
     */
    public static final Producto PRODUCTO = new Producto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductoRecord> getRecordType() {
        return ProductoRecord.class;
    }

    /**
     * The column <code>PLUGINTAPESTRY.PRODUCTO.ID</code>.
     */
    public final TableField<ProductoRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PLUGINTAPESTRY.PRODUCTO.NOMBRE</code>.
     */
    public final TableField<ProductoRecord, String> NOMBRE = createField(DSL.name("NOMBRE"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>PLUGINTAPESTRY.PRODUCTO.DESCRIPCION</code>.
     */
    public final TableField<ProductoRecord, String> DESCRIPCION = createField(DSL.name("DESCRIPCION"), SQLDataType.VARCHAR(5000).nullable(false), this, "");

    /**
     * The column <code>PLUGINTAPESTRY.PRODUCTO.CANTIDAD</code>.
     */
    public final TableField<ProductoRecord, Long> CANTIDAD = createField(DSL.name("CANTIDAD"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>PLUGINTAPESTRY.PRODUCTO.FECHA</code>.
     */
    public final TableField<ProductoRecord, LocalDateTime> FECHA = createField(DSL.name("FECHA"), SQLDataType.LOCALDATETIME(6), this, "");

    private Producto(Name alias, Table<ProductoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Producto(Name alias, Table<ProductoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PLUGINTAPESTRY.PRODUCTO</code> table reference
     */
    public Producto(String alias) {
        this(DSL.name(alias), PRODUCTO);
    }

    /**
     * Create an aliased <code>PLUGINTAPESTRY.PRODUCTO</code> table reference
     */
    public Producto(Name alias) {
        this(alias, PRODUCTO);
    }

    /**
     * Create a <code>PLUGINTAPESTRY.PRODUCTO</code> table reference
     */
    public Producto() {
        this(DSL.name("PRODUCTO"), null);
    }

    public <O extends Record> Producto(Table<O> child, ForeignKey<O, ProductoRecord> key) {
        super(child, key, PRODUCTO);
    }

    @Override
    public Schema getSchema() {
        return Plugintapestry.PLUGINTAPESTRY;
    }

    @Override
    public Identity<ProductoRecord, Long> getIdentity() {
        return (Identity<ProductoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductoRecord> getPrimaryKey() {
        return Keys.PK_PRODUCTO;
    }

    @Override
    public List<UniqueKey<ProductoRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductoRecord>>asList(Keys.PK_PRODUCTO);
    }

    @Override
    public Producto as(String alias) {
        return new Producto(DSL.name(alias), this);
    }

    @Override
    public Producto as(Name alias) {
        return new Producto(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Producto rename(String name) {
        return new Producto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Producto rename(Name name) {
        return new Producto(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Long, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
