/*
 * This file is generated by jOOQ.
 */
package io.github.picodotdev.plugintapestry.entities.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProducto extends Serializable {

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.ID</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.ID</code>.
     */
    public Long getId();

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.NOMBRE</code>.
     */
    public void setNombre(String value);

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.NOMBRE</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getNombre();

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.DESCRIPCION</code>.
     */
    public void setDescripcion(String value);

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.DESCRIPCION</code>.
     */
    @NotNull
    @Size(max = 5000)
    public String getDescripcion();

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.CANTIDAD</code>.
     */
    public void setCantidad(Long value);

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.CANTIDAD</code>.
     */
    public Long getCantidad();

    /**
     * Setter for <code>PLUGINTAPESTRY.PRODUCTO.FECHA</code>.
     */
    public void setFecha(LocalDateTime value);

    /**
     * Getter for <code>PLUGINTAPESTRY.PRODUCTO.FECHA</code>.
     */
    public LocalDateTime getFecha();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IProducto
     */
    public void from(IProducto from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IProducto
     */
    public <E extends IProducto> E into(E into);
}
