/**
 * This class is generated by jOOQ
 */
package io.github.picodotdev.blogbitix.multidatabase.jooq.purchases;


import io.github.picodotdev.blogbitix.multidatabase.jooq.purchases.tables.Purchase;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PURCHASES
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PURCHASES.PURCHASE
	 */
	public static final Purchase PURCHASE = io.github.picodotdev.blogbitix.multidatabase.jooq.purchases.tables.Purchase.PURCHASE;
}
